Update double_spend.md
lostinbitcoin/categories pull request #122
Opened 2024-04-02 04:15 UTC by usagicrypto

ロストインビットコインの記事を楽しく拝見しています。翻訳に取り組みました。gitの操作に不慣れなため、内容に不備等あればご教示いただきたく存じます。よろしくお願いいたします。

2024-04-04 05:42 UTC, lostinbitcoin requested changes
プルリクエストありがとうございます。訳文は正確です。より読みやすくするため、以下のように修正いただくことは可能でしょうか？

二重支払いとは、決済の際に、受取人に支払いが完了したと信じ込ませて、支払人が支払いを免れる詐欺行為で、同じお金を２回使うことができる場合に発生します。
テキストや画像など電子データは複製が容易です。この特性は電子マネーにも該当し、二重支払い問題の根源でもあります。電子マネーの受信者は、受け取ったお金が他の誰かに送られていないことをどうしたら確信できるでしょうか？決済ネットワークの参加者は、二重支払いの発生をどのように阻止できるのでしょうか？
ビットコインは、誰でも自由に閲覧可能な分散型台帳を採用することで、二重支払い問題を解決しました。ビットコインを送金すると、送金者が所有していたコインは破棄され、受金者は新規作成されたコインを入手します。送金者のコインが破棄されたことは台帳に記録されるので、そのコインで二重支払いを試みても、受金者とネットワーク参加者は容易に不正送金だと判断できます。

2024-04-05 07:05 UTC, merged

2024-04-05 07:15 UTC, lostinbitcoin commented
ありがとうございます。マージしたので近日中にサイトに反映させていただきます。プロフに掲載のLNアドレスに報酬をお送りしました。今後もぜひご協力お願いします。

2024-05-02 09:30 UTC, lostinbitcoin commented
返信遅くなって申し訳ありません。
この度はご協力ありがとうございました。ぜひ、また気軽にPRください。
お尋ねするのを忘れてましたが、ロストインのトップページ下部にコントリビュータとしてXのプロフを貼っても良いでしょうか？

2024-05-02 12:37 UTC, usagicrypto commented
コントリビュータのXのプロフ掲載の件、大丈夫です。
嬉しいです！よろしくお願いいたします。

2024-05-03 04:02 UTC, lostinbitcoin commented
ありがとうございます。プロフ掲載させていただきました。弊社のXアカウントから、usagiさんのPRをマージさせていただいたこと投稿させていただきますね。githubに不慣れでPRを出すのに躊躇してる方の後押しになると思うので。
https://lostinbitcoin.jp/

2024-05-03 06:58 UTC, usagicrypto commented
プロフの掲載ありがとうございます。
Xの投稿も承知しました！私もビットコインに興味があるけどgithubに抵抗がある人の1人だったので、お役に立てば幸いです。